version: "3.9"
services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    

  app:
    build: .
    ports:  
      - 8090:8090
    environment:
      APP_NAME: swiftdata
      PORT: 8090
      DB_URI: mongodb://mongo_db:27017/swift-data
      TEST_PORT: 8082
    depends_on:
       - mongo_db
 
    

volumes:
  mongo_db: {}

