version: "3.9"
services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:  
      - 8090:8090
    environment:
      APP_NAME: swiftdata
      PORT: 8090
      DB_URI: mongodb://mongo_db:27017/swift-data
      TEST_PORT: 8082
    depends_on:
      mongo_db:
        condition: service_healthy

volumes:
  mongo_db: {}
